language: php
php:
  - 5.3
  - 5.4

before_script:
  - echo "Instalando dependencias"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS blog;' -uroot; 
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash
  
script:
  - phpunit --configuration teste/phpunit-travis.xml